# @Author: Haibin Lee <haibin>
# @Date:   2020-10-30T21:15:43+08:00
# @Email:  haibin.li@newtouch.com
# @Last modified by:   haibin
# @Last modified time: 2020-11-11T16:23:34+08:00
# @Copyright: www.newtouch.com



- name: "生成机构 {{ agency.name }} 部署文件"
  command: "./generator --build_install_package ./meta/peers_{{ agency.main_group_id }}.txt ./fisco_deploy_agency_{{ agency.name }}/ {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

- block:
    - name: "机构 {{ agency.name }} 为现有节点初始化 {{ agency.extra_group_id }} 群组"
      command: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}/"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      changed_when: false
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}/"

    - name: "机构 {{ agency.name }} 添加其它组 {{ agency.extra_group_id }} 节点信息"
      command: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}/"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}/"
      changed_when: false
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id != ''
