# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: console.yml
# @Last modified by:   haibin
# @Last modified time: 2020-11-30T19:30:27+08:00
# @License: GNU General Public License v3.0


- name: 检查机构 {{ agency.name }} 的 console 控制台
  stat:
    path: "{{ fisco_workdir }}/agency_{{ agency.name }}/console/"
  register: __console_st

- name: "安装机构 {{ agency.name }} 的 console 控制台"
  command: ./generator --download_console ./ --console_version 1.1.0 --cdn
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false
  when: not __console_st.stat.exists

- block:
    - name: "清空控制台的已有节点连接信息"
      xml:
        path: "{{ fisco_workdir }}/agency_{{ agency.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='groupChannelConnectionsConfig']/x:property[@name='allChannelConnections']/x:list/x:bean[@id='group{{ agency.main_group_id }}']/x:property[@name='connectionsStr']/x:list/*"
        namespaces:
          x: http://www.springframework.org/schema/beans
        state: absent
      changed_when: false

    - name: "重新添加节点连接信息到控制台配置"
      xml:
        path: "{{ fisco_workdir }}/agency_{{ agency.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='groupChannelConnectionsConfig']/x:property[@name='allChannelConnections']/x:list/x:bean[@id='group{{ agency.main_group_id }}']/x:property[@name='connectionsStr']/x:list"
        namespaces:
          x: http://www.springframework.org/schema/beans
        add_children:
          - value: "{{ item.split(':')[2] }}:{{ item.split(':')[4] }}"
        pretty_print: true
      loop: "{{ node_list }}"
      loop_control:
        label: "{{ item.split(':')[2] }}:{{ item.split(':')[4] }} 添加到 {{ fisco_workdir }}/agency_{{ agency.name }}/console/conf/applicationContext.xml"
      when:
        - ((item.split(':')[1] | int) == agency.main_group_id) or (agency.main_group_id|quote in item.split(':')[6])
        - lookup('file', fisco_workdir + '/agency_' + agency.name + '/console/conf/applicationContext.xml') | regex_search(item.split(':')[2] + ':' + item.split(':')[4]) == None
      changed_when: false

    - name: 国密版 | 修改控制台国密配置
      xml:
        path: "{{ fisco_workdir }}/agency_{{ agency.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='encryptType']/x:constructor-arg"
        attribute: value
        value: "1"
        namespaces:
          x: http://www.springframework.org/schema/beans
        pretty_print: true
      when: fisco_gm_enabled

    - name: 修改控制台机构名称
      xml:
        path: "{{ fisco_workdir }}/agency_{{ agency.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='channelService']/x:property[@name='agencyName']"
        attribute: value
        value: "{{ agency.name }}"
        namespaces:
          x: http://www.springframework.org/schema/beans
        pretty_print: true

  when: (__node_list_update is changed) or (not __console_st.stat.exists)
