# @Author: Haibin Lee <haibin>
# @Date:   2020-10-30T21:15:43+08:00
# @Email:  haibin.li@newtouch.com
# @Last modified by:   haibin
# @Last modified time: 2020-11-11T16:25:22+08:00
# @Copyright: www.newtouch.com



- name: "生成创世区块"
  command: "./generator --create_group_genesis ./group {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

- name: 分发创世区块
  copy:
    src: "{{ fisco_workdir }}/agency_{{ agency.name }}/group/group.{{ agency.main_group_id }}.genesis"
    dest: "{{ fisco_workdir }}/agency_{{ item }}/meta/group.{{ agency.main_group_id }}.genesis"
  loop: "{{ groups['fisco_agency_group_' + agency.main_group_id|quote] }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ item }}/meta/group.{{ agency.main_group_id }}.genesis"
