- name: "创建组 {{ agency.main_group_id }} 的节点 P2P 连接地址文件"
  template:
    src: main_group_peers.txt.j2
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ agency.main_group_id }}.txt"
    backup: true

- name: "创建组 {{ agency.extra_group_id }} 的节点 P2P 连接地址文件"
  template:
    src: extra_group_peers.txt.j2
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ extra_group_id }}.txt"
    backup: true
  loop: "{{ agency.extra_group_id }}"
  loop_control:
    loop_var: extra_group_id
    label: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ extra_group_id }}.txt"
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id != ''

- name: "发送机构证书到同组创世区块机构 {{ agency.name }}"
  shell: "cp {{ fisco_workdir }}/agency_{{ item }}/agency_{{ item }}_node_info/{{ fisco_gm_enabled | ternary('gm', '') }}cert*.crt {{ fisco_workdir }}/agency_{{ agency.name }}/meta/"
  changed_when: false
  loop: "{{ groups['fisco_agency_group_' + agency.main_group_id|quote ] }}"
  when:
    - agency.create_genesis | default(false)
    - item != agency.name
