- name: 检查 console 控制台
  stat:
    path: "{{ fisco_workdir }}/agency_{{ item.name }}/console/"
  loop: "{{ agencies }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ item.name }}/console/"
  register: __console_st

- name: 生成 console 控制台
  command: ./generator --download_console ./ --cdn
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ item.item.name }}"
  loop: "{{ __console_st.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  changed_when: false
  when: not item.stat.exists

- block:
    - name: "清空控制台的已有节点连接信息"
      xml:
        path: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='groupChannelConnectionsConfig']/x:property[@name='allChannelConnections']/x:list/x:bean[@id='group{{ item.group_id }}']/x:property[@name='connectionsStr']/x:list/*"
        namespaces:
          x: http://www.springframework.org/schema/beans
        state: absent
      loop: "{{ agencies }}"
      loop_control:
        label: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"
      changed_when: false

    - name: "重新添加节点连接信息到控制台配置"
      xml:
        path: "{{ fisco_workdir }}/agency_{{ item.0.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='groupChannelConnectionsConfig']/x:property[@name='allChannelConnections']/x:list/x:bean[@id='group{{ item.0.group_id }}']/x:property[@name='connectionsStr']/x:list"
        namespaces:
          x: http://www.springframework.org/schema/beans
        add_children:
          - value: "{{ item.1.split(':')[2] }}:{{ item.1.split(':')[4] }}"
        pretty_print: true
      with_nested:
        - "{{ agencies }}"
        - "{{ node_list }}"
      loop_control:
        label: "{{ item.1.split(':')[2] }}:{{ item.1.split(':')[4] }} 添加到 {{ fisco_workdir }}/agency_{{ item.0.name }}/console/conf/applicationContext.xml"
      when:
        - ((item.1.split(':')[1] | int) == item.0.group_id) or (item.0.group_id|quote in item.1.split(':')[6])
        - lookup('file', fisco_workdir + '/agency_' + item.0.name + '/console/conf/applicationContext.xml') | regex_search(item.1.split(':')[2] + ':' + item.1.split(':')[4]) == None
      changed_when: false

    - name: 国密版 | 修改控制台国密配置
      xml:
        path: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='encryptType']/x:constructor-arg"
        attribute: value
        value: "1"
        namespaces:
          x: http://www.springframework.org/schema/beans
        pretty_print: true
      loop: "{{ agencies }}"
      loop_control:
        label: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"
      when: fisco_gm_enabled

    - name: 修改控制台机构名称
      xml:
        path: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"
        xpath: "/x:beans/x:bean[@id='channelService']/x:property[@name='agencyName']"
        attribute: value
        value: "{{ item.name }}"
        namespaces:
          x: http://www.springframework.org/schema/beans
        pretty_print: true
      loop: "{{ agencies }}"
      loop_control:
        label: "{{ fisco_workdir }}/agency_{{ item.name }}/console/conf/applicationContext.xml"

    - name: 备份当前 node_list.yml
      copy:
        src: "{{ fisco_workdir }}/node_list.yml"
        dest: "{{ fisco_workdir }}/node_list.yml.backup~"

  when: __node_list_update is changed

- name: 生成部署报告
  template:
    src: summary.j2
    dest: "{{ fisco_workdir }}/summary.txt"
    # backup: true
