# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: pre_tasks.yml
# @Last modified by:   haibin
# @Last modified time: 2020-11-17T10:49:55+08:00
# @License: GNU General Public License v3.0



- name: "检查 generator 目录"
  stat:
    path: "{{ fisco_workdir }}/generator"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir

- block:
    - include_tasks: enterprise/install_generator.yml
  when: not __generator_dir.stat.exists

- name: "生成节点清单 {{ fisco_workdir }}/node_list.yml"
  template:
    src: "node_list.j2"
    dest: "{{ fisco_workdir }}/node_list.yml"
    backup: true
  notify: "备份当前 node_list.yml"
  register: __node_list_update

- name: 加载当前节点清单
  include_vars: "{{ fisco_workdir }}/node_list.yml"

- name: 设置动态变量
  set_fact:
    node_list: "{{ node_list | sort }}"
    pre_node_list_path: "{{ lookup('pipe', 'ls -1tr ' + fisco_workdir + '/node_list.yml.*~ | tail -n1') }}"
    fisco_group_id_list: "{{ agencies | map(attribute='main_group_id') | unique }}"

- name: 检查每个群组是否有且只有 1 个创世区块机构
  fail:
    msg: "群组 {{ item }} 没有指定或存在多个创世区块机构。请排查 {{ inventory_dir }}/group_vars/all/init.yml 文件并确定组内，有且只有 1 个创世区块机构（拥有 create_genesis: true 属性）。"
  loop: "{{ fisco_group_id_list }}"
  loop_control:
    label: "检查群组 {{ item }}"
  when: >-
    ( agencies
        | selectattr('main_group_id', '==', item)
        | selectattr('create_genesis', 'defined')
        | selectattr('create_genesis')
        | list
        | count
    ) != 1

- name: 节点分组 | 根据机构名称
  add_host:
    name: "{{ item }}"
    group: "fisco_agency_{{ item.split(':')[0] }}"
  loop: "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.split(':')[2:4] | join(':') }} 添加到 fisco_agency_{{ item.split(':')[0] }} 组"

- name: 节点分组 | 根据 GROUP ID
  add_host:
    name: "{{ item.1 }}"
    group: "fisco_node_group_{{ item.0 }}"
  with_nested:
    - "{{ fisco_group_id_list }}"
    - "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.1.split(':')[2:4] | join(':') }} 添加到 fisco_group_{{ item.0 }} 组"
  when: item.0|quote == item.1.split(':')[1] or item.0|quote in item.1.split(':')[6]

- name: 机构分组 | 根据 main_group_id
  add_host:
    name: "{{ item.name }}"
    group: "fisco_agency_group_{{ item.main_group_id }}"
  loop: "{{ agencies }}"
  loop_control:
    label: "机构 {{ item.name }} 添加到 fisco_agency_group_{{ item.main_group_id }} 组"

- name: 机构分组 | 根据 extra_group_id
  add_host:
    name: "{{ item.0.name }}"
    group: "fisco_agency_group_{{ item.1 }}"
  loop: "{{ agencies | selectattr('extra_group_id', 'defined') | subelements('extra_group_id') }}"
  loop_control:
    label: "机构 {{ item.0.name }} 添加到 fisco_agency_group_{{ item.1 }} 组"

- name: 新增节点加入 'fisco_expand_nodes' 组
  add_host:
    name: "{{ item }}"
    group: "fisco_expand_nodes"
  loop: "{{ node_list }}"
  loop_control:
    label: "{{ item.split(':')[0:4] | join(':') }} 添加到 fisco_expand_nodes 组"
  when:
    - pre_node_list_path is truthy
    - item not in lookup('file', pre_node_list_path)
