- name: "检查 generator 目录"
  stat:
    path: "{{ fisco_workdir }}/generator"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir

- block:
    - include_tasks: enterprise/install_generator.yml
  when: not __generator_dir.stat.exists

- name: "生成节点清单 {{ fisco_workdir }}/node_list.yml"
  template:
    src: "node_list.j2"
    dest: "{{ fisco_workdir }}/node_list.yml"
    backup: true
  register: __node_list_update

- name: 加载当前节点清单
  include_vars: "{{ fisco_workdir }}/node_list.yml"

- name: 设置动态变量
  set_fact:
    node_list: "{{ node_list | sort }}"
    pre_node_list_path: "{{ lookup('pipe', 'ls -1tr ' + fisco_workdir + '/node_list.yml.*~ || exit 0 | tail -n1') }}"

- name: 创建新增节点清单 'new_node_list'
  set_fact:
    new_node_list: "{{ new_node_list }} + [ '{{ item }}' ]"
  loop: "{{ node_list }}"
  when:
    - pre_node_list_path != ''
    - item not in lookup('file', pre_node_list_path)
