- name: "检查 generator 目录"
  stat:
    path: "{{ fisco_workdir }}/generator"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir

- block:
    - include_tasks: enterprise/install_generator.yml
  when: not __generator_dir.stat.exists

- name: "生成节点清单 {{ fisco_workdir }}/node_list.yml"
  template:
    src: "node_list.j2"
    dest: "{{ fisco_workdir }}/node_list.yml"
    backup: true
  register: __node_list_update

- name: 加载当前节点清单
  include_vars: "{{ fisco_workdir }}/node_list.yml"

- name: 设置动态变量
  set_fact:
    node_list: "{{ node_list | sort }}"
    pre_node_list_path: "{{ lookup('pipe', 'ls -1tr ' + fisco_workdir + '/node_list.yml.*~ || exit 0 | tail -n1') }}"
    fisco_group_id_list: "{{ agencies | map(attribute='main_group_id') | unique }}"

- name: 节点分组 | 根据机构名称
  add_host:
    name: "{{ item }}"
    group: "fisco_agency_{{ item.split(':')[0] }}"
  loop: "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.split(':')[2:4] }} 添加到 fisco_agency_{{ item.split(':')[0] }} 组"

- name: 节点分组 | 根据 GROUP ID
  add_host:
    name: "{{ item.1 }}"
    group: "fisco_node_group_{{ item.0 }}"
  with_nested:
    - "{{ fisco_group_id_list }}"
    - "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.1.split(':')[2:4] }} 添加到 fisco_group_{{ item.0 }} 组"
  when: item.0|string == item.1.split(':')[1] or item.0|string in item.1.split(':')[6]

- name: 机构分组 | 根据 main_group_id
  add_host:
    name: "{{ item.name }}"
    group: "fisco_agency_group_{{ item.main_group_id }}"
  loop: "{{ agencies }}"
  loop_control:
    label: "机构 {{ item.name }} 添加到 fisco_agency_group_{{ item.main_group_id }} 组"

- name: 机构分组 | 根据 extra_group_id
  add_host:
    name: "{{ item.0.name }}"
    group: "fisco_agency_group_{{ item.1 }}"
  loop: "{{ agencies | selectattr('extra_group_id', 'defined') | subelements('extra_group_id') }}"
  loop_control:
    label: "机构 {{ item.0.name }} 添加到 fisco_agency_group_{{ item.1 }} 组"

- name: 新增节点加入 'fisco_expand_nodes' 组
  add_host:
    name: "{{ item }}"
    group: "fisco_expand_nodes"
  loop: "{{ node_list }}"
  loop_control:
    label: "{{ item.split(':')[2:4] }} 添加到 fisco_expand_nodes 组"
  when:
    - pre_node_list_path != ''
    - item not in lookup('file', pre_node_list_path)
