# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: prepare.yml
# @Last modified by:   haibin
# @Last modified time: 2020-11-11T17:36:23+08:00
# @License: GNU General Public License v3.0



- block:
    - name: "Create {{ ansible_user_dir }}/fisco"
      file:
        path: "{{ ansible_user_dir }}/fisco"
        state: directory

    - name: Installing tools
      become: true
      package:
        name:
          - openssl
          - curl
          - default-jdk

    - name: Downloading build_chain.sh script
      get_url:
        url: "{{ fisco_build_chain_url }}"
        dest: "{{ ansible_user_dir }}/fisco/"

    - name: Downloading download_console.sh
      get_url:
        url: "{{ fisco_download_console_url }}"
        dest: "{{ ansible_user_dir }}/fisco/"
  when: fisco_deploy_mode == 'single'
