# @Author: Haibin Lee <haibin>
# @Date:   2020-10-30T21:15:43+08:00
# @Email:  haibin.li@newtouch.com
# @Last modified by:   haibin
# @Last modified time: 2020-11-11T16:29:15+08:00
# @Copyright: www.newtouch.com



# 注意：本剧本只用于测试场景，生产环境请手动传送对应的压缩包，并解压执行。
- hosts: test
  # serial: 1
  vars_files:
    - roles/fisco_bcos/defaults/main.yml
    - inventories/sample/deploy/node_list.yml
  tasks:
    - name: 查找节点配置文件夹路径
      find:
        paths: "{{ fisco_workdir }}"
        patterns: "node_*"
        file_type: directory
        recurse: true
        use_regex: true
      register: node_paths
      delegate_to: localhost

    - name: 停止
      shell: "find /opt/fisco_nodes/node_{{ ansible_host }}_* -type f -name stop.sh -exec {} \\; || exit 0"
      changed_when: false

    - pause:
        seconds: 3

    - name: 同步节点文件
      become: true
      synchronize:
        src: "{{ item.0 }}"
        dest: /opt/fisco_nodes
        use_ssh_args: true
        rsync_opts:
          - "--chown=vagrant:vagrant"
        delete: true
      with_nested:
        - "{{ node_paths.files | map(attribute='path') | reject('search', 'meta') | sort }}"
        - "{{ node_list | sort }}"
      loop_control:
        label: "{{ item.0 }}"
      when:
        - ansible_host == item.1.split(':')[2]
        - ('node_' + item.1.split(':')[2] + '_' + item.1.split(':')[3]) == (item.0 | basename)
      register: __sync_st

    - name: 启动
      raw: "find /opt/fisco_nodes/node_{{ ansible_host }}_* -type f -name start.sh -exec {} \\;"
      changed_when: false

    - name: 查找控制台文件夹路径
      find:
        paths: "{{ fisco_workdir }}"
        patterns: "console"
        file_type: directory
        recurse: true
        use_regex: true
      register: console_paths
      delegate_to: localhost

    - name: 同步控制台文件
      become: true
      synchronize:
        src: "{{ item.0 }}"
        dest: /opt/fisco_nodes
        use_ssh_args: true
        rsync_opts:
          - "--chown=vagrant:vagrant"
        delete: true
      with_nested:
        - "{{ console_paths.files | map(attribute='path') | reject('search', 'contract') | sort }}"
        - "{{ agencies }}"
      loop_control:
        label: "{{ item.0 }}"
      when:
        - item.0 | regex_search('agency_' + item.1.name)
        - item.1 | regex_search(ansible_host)
      register: __console_sync

    - name: 安装 jdk
      become: true
      apt:
        name: default-jre
        update_cache: true
        autoclean: true
        autoremove: true
      when: __console_sync is changed
