# @Author: Haibin Lee <haibin>
# @Date:   2020-11-24T10:45:09+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: generate_archimate.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-30T16:15:43+08:00
# @Copyright: Copyright 2020 the original author or authors.



- block:
    - name: YUM | 安装 java-1.8.0-openjdk
      package:
        name:
          - java-1.8.0-openjdk
          - graphviz
      when:
        - lookup('pipe', 'java -version || echo "false"') == 'false'
        - ansible_os_family == 'RedHat'
    - name: APT | 安装 default-jre
      package:
        name:
          - default-jre
          - graphviz
      when:
        - lookup('pipe', 'java -version || echo "false"') == 'false'
        - ansible_os_family == 'Debian'
    - name: PACMAN | 安装 jre8-openjdk
      package:
        name:
          - jre8-openjdk
          - graphviz
      when:
        - lookup('pipe', 'java -version || echo "false"') == 'false'
        - ansible_os_family == 'Archlinux'
    - name: 未支持系统
      fail:
        msg: "不支持在当前系统自动安装 JRE，请参考相关方法手动安装。"
      when:
        - lookup('pipe', 'java -version || echo "false"') == 'false'
        - ansible_os_family not in ['Debian', 'RedHat', 'Archlinux']
    - name: 创建 /usr/share/java/plantuml/ 目录
      file:
        path: /usr/share/java/plantuml/
        state: directory
    - name: 下载 plantuml
      get_url:
        url: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        dest: /usr/share/java/plantuml/plantuml.jar
        mode: 0644
    - name: 创建 /usr/bin/plantuml 执行脚本
      copy:
        content: |
          #!/bin/sh
          exec /usr/bin/java -jar '/usr/share/java/plantuml/plantuml.jar' "$@"
        dest: /usr/bin/plantuml
        mode: 0755
  when: >-
    lookup('pipe', 'which plantuml || echo "false"') == 'false'

- name: "创建 {{ fisco_workdir }}/archimate 目录"
  file:
    path: "{{ fisco_workdir }}/archimate"
    state: directory
  when: "not lookup('fileglob', fisco_workdir + '/archimate')"

- name: 生成联盟链 puml 文件
  template:
    src: "chain_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/chain_topo.puml"
    validate: "plantuml -checkonly %s"

- name: 生成机构 puml 文件
  template:
    src: "agency_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"
    validate: "plantuml -checkonly %s"
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"

- name: 生成图片文件
  command: "plantuml -nbthread auto {{ item | basename }}"
  args:
    chdir: "{{ fisco_workdir }}/archimate/"
  changed_when: false
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
  loop_control:
    label: "{{ item | regex_replace('.puml', '.png') }}"

- name: 清理 puml 文件
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
