# @Author: Haibin Lee <haibin>
# @Date:   2020-11-24T10:45:09+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: generate_archimate.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-09T13:40:03+08:00
# @Copyright: Copyright 2020 the original author or authors.



- name: 安装 plantuml
  become: yes
  package:
    name:
      - plantuml
      - graphviz
  when: not lookup('pipe', 'which plantuml')

- name: "创建 {{ fisco_workdir }}/archimate 目录"
  file:
    path: "{{ fisco_workdir }}/archimate"
    state: directory
  when: not lookup('fileglob', fisco_workdir + '/archimate')

- name: 生成联盟链 puml 文件
  template:
    src: "chain_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/chain_topo.puml"
    validate: "plantuml -checkonly %s"

- name: 生成机构 puml 文件
  template:
    src: "agency_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"
    validate: "plantuml -checkonly %s"
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"

- name: 生成图片文件
  command: "plantuml -nbthread auto {{ item | basename }}"
  args:
    chdir: "{{ fisco_workdir }}/archimate/"
  changed_when: false
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
  loop_control:
    label: "{{ item | regex_replace('.puml', '.png') }}"

- name: 清理 puml 文件
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
