# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: build_install_package.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-21T12:04:58+08:00
# @License: GNU General Public License v3.0


- name: "拷贝同组创世区块"
  copy:
    src: "{{ fisco_workdir }}/agency_{{ item.name }}/group/group.{{ item.main_group_id }}.genesis"
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  loop: "{{ agencies }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  when:
    - item.main_group_id == agency.main_group_id
    - item.create_genesis | default(false)

- name: 拷贝扩展群组的创世区块
  copy:
    src: "{{ fisco_workdir }}/agency_{{ item.name }}/group/group.{{ item.main_group_id }}.genesis"
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  loop: "{{ agencies }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id is truthy
    - item.main_group_id in agency.extra_group_id
    - item.create_genesis | default(false)

- name: "生成机构 {{ agency.name }} 部署文件"
  command: "./generator --build_install_package ./meta/peers_{{ agency.main_group_id }}.txt ./fisco_deploy_agency_{{ agency.name }}/ {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

- block:
    - name: "群组扩展 | 机构 {{ agency.name }} 为现有节点初始化 {{ agency.extra_group_id }} 群组"
      command: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}/"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      changed_when: false
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}/"

    - name: "群组扩展 | 机构 {{ agency.name }} 添加其它组 {{ agency.extra_group_id }} 节点信息"
      command: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}/"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}/"
      changed_when: false
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id is truthy

# https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/configuration.html#config-ini
- name: 更新 listen_ip。如果是公网 IP，则监听 0.0.0.0。
  ini_file:
    path: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}/node_{{ item.split(':')[2] }}_{{ item.split(':')[3] }}/config.ini"
    section: "p2p"
    option: "listen_ip"
    value: "{{ item.split(':')[2] | ipaddr('private') | ternary(item.split(':')[2]|quote, '0.0.0.0') }}"
  loop: "{{ node_list }}"
  loop_control:
    label: "修改 {{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}/node_{{ item.split(':')[2] }}_{{ item.split(':')[3] }}/config.ini"
  when: "item.split(':')[0] == agency.name"
