- debug:
    msg: "###################### 开始机构 {{ agency.name }} 初始化 ######################"

- include_tasks: check_list.yml

- block:
    - name: "检查机构目录是否存在"
      stat:
        path: "{{ fisco_workdir }}/agency_{{ item.name }}"
      loop: "{{ agencies }}"
      loop_control:
        label: "{{ fisco_workdir }}/agency_{{ item.name }}"
      register: __agency_dir

    - name: "初始化机构目录"
      command: >-
        rsync -a --exclude-from '{{ role_path }}/files/rsync-exclude-list.txt' \
          {{ fisco_workdir }}/generator/ {{ item.invocation.module_args.path }}
      args:
        chdir: "{{ fisco_workdir }}/generator/"
        warn: false
      loop: "{{ __agency_dir.results }}"
      loop_control:
        label: "{{ item.invocation.module_args.path }}"
      when: not item.stat.exists

- include_tasks:
    file: generate_agency_certificate.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency_cert

- include_tasks:
    file: generate_agency_config.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency_config

# 同组
- block:
    - name: “创世区块机构 {{ __group_leader }} 发送节点信息到机构 {{ agency.name }}”
      copy:
        src: "{{ fisco_workdir }}/agency_{{ __group_leader }}/agency_{{ __group_leader }}_node_info/peers.txt"
        dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ __group_leader }}.txt"

    - name: "机构 {{ agency.name }} 发送节点信息到创世区块机构 {{ __group_leader }}"
      copy:
        src: "{{ fisco_workdir }}/agency_{{ agency.name }}/agency_{{ agency.name }}_node_info/peers.txt"
        dest: "{{ fisco_workdir }}/agency_{{ __group_leader }}/meta/peers_{{ agency.name }}.txt"

    - name: "发送机构 {{ agency.name }} 证书到创世区块机构 {{ __group_leader }}"
      copy:
        src: "{{ item }}"
        dest: "{{ fisco_workdir }}/agency_{{ __group_leader }}/meta/{{ item | basename }}"
      with_fileglob:
        - "{{ fisco_workdir }}/agency_{{ agency.name }}/agency_{{ agency.name }}_node_info/*.crt"

    - name: "在机构 {{ __group_leader }} 生成群组 {{ agency.group_id }} 创世区块"
      command: ./generator --create_group_genesis ./group
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ __group_leader }}"
      changed_when: false

    - name: "拷贝创世区块 'group.{{ agency.group_id }}.genesis' 到 {{ fisco_workdir }}/agency_{{ agency.name }}/meta/"
      copy:
        src: "{{ fisco_workdir }}/agency_{{ __group_leader }}/group/group.{{ agency.group_id }}.genesis"
        dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ agency.group_id }}.genesis"
  when: agency.name != __group_leader

# 异组
- block:
    - include_tasks: agency_join.yml
      loop: "{{ __join_to_agencies }}"
      loop_control:
        loop_var: join_to_agency
  when:
    - agency.group_join_to is defined
    - agency.group_join_to != []

- name: "生成机构 {{ agency.name }} 部署文件"
  command: ./generator --build_install_package ./meta/peers_{{ __group_leader }}.txt ./fisco_deploy_agency_{{ agency.name }}/
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

- name: "生成创世区块机构 {{ __group_leader }} 部署文件"
  command: ./generator --build_install_package ./meta/peers_{{ agency.name }}.txt ./fisco_deploy_agency_{{ __group_leader }}/
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ __group_leader }}"
  changed_when: false
