- name: Leader | 生产部署文件
  command: ./generator --build_install_package ./meta/peers_{{ item }}.txt ./node_{{ agency_name }}/
  args:
    chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
  loop: "{{ __agency_follower_name }}"
  when: inventory_hostname in groups['group_leader']
  changed_when: false

- name: Follower | 生成部署文件
  command: ./generator --build_install_package ./meta/peers_{{ __agency_leader_name }}.txt ./node_{{ agency_name }}/
  args:
    chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
  when: inventory_hostname in groups['group_follower']
  changed_when: false

- name: 生成压缩包
  archive:
    path: "{{ inventory_dir }}/agency_{{ agency_name }}/node_{{ agency_name }}"
    dest: "{{ inventory_dir }}/agency_{{ agency_name }}/node_{{ agency_name }}.tgz"
