- name: "发送机构 {{ agency.name }} 证书到其它群组机构 {{ join_to.name }}"
  copy:
    src: "{{ item }}"
    dest: "{{ fisco_workdir }}/agency_{{ join_to.name }}/meta/{{ item | basename }}"
  with_fileglob:
    - "{{ fisco_workdir }}/agency_{{ agency.name }}/agency_{{ agency.name }}_node_info/*.crt"

- name: "机构 {{ agency.name }} 发送节点信息到其它群组机构 {{ join_to.name }}"
  copy:
    src: "{{ fisco_workdir }}/agency_{{ agency.name }}/agency_{{ agency.name }}_node_info/peers.txt"
    dest: "{{ fisco_workdir }}/agency_{{ join_to.name }}/meta/peers_{{ agency.name }}.txt"

- name: "其它群组机构 {{ join_to.name }} 发送节点信息到机构 {{ agency.name }}"
  copy:
    src: "{{ fisco_workdir }}/agency_{{ join_to.name }}/agency_{{ agency.name }}_node_info/peers.txt"
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ agency.name }}.txt"
