- name: 检查同组内是否有且只有 1 个创世区块机构
  fail:
    msg: "群组 {{ agency.group_id }} 没有指定或存在多个创世区块机构。请排查 {{ inventory_dir }}/group_vars/all/init.yml 文件并确定同组内，有且只有 1 个创世区块机构（拥有 create_genesis: true 属性）。"
  when: >-
    ( agencies
        | selectattr('group_id', '==', agency.group_id)
        | selectattr('create_genesis', 'defined')
        | selectattr('create_genesis')
        | map(attribute='name')
        | list
        | count
    ) != 1

- block:
    - name: 获取同组创世区块机构名称
      set_fact:
        __group_leader: >-
          {{ agencies
            | selectattr('group_id', '==', agency.group_id)
            | selectattr('create_genesis', 'defined')
            | selectattr('create_genesis')
            | map(attribute='name')
            | list
            | first
          }}

    - debug:
        msg: "组 {{ agency.group_id }} 的创世区块机构是 {{ __group_leader }}"

    - name: "记录创世区块机构名称到 {{ fisco_workdir }}/group_vars/all/group_leader.yml"
      lineinfile:
        path: "{{ inventory_dir }}/group_vars/all/group_leader.yml"
        line: "group_{{ agency.group_id }}_leader: {{ __group_leader }}"
        regexp: "^group_{{ agency.group_id }}_leader: "
        create: true
        backup: true

# - block:
#     - name: 获取同组机构节点列表
#       set_fact:
#         __same_group_nodes: >-
#           {{ agencies
#             | selectattr('group_id', '==', agency.group_id)
#             | sum(attribute='nodes', start=[])
#             | list
#           }}
#     - debug:
#         msg: "组 {{ agency.group_id }} 一共有节点 {{ __same_group_nodes }}"

- block:
    - name: 获取其它目标的机构信息
      set_fact:
        __join_to_agencies: >-
          {{ agencies
            | selectattr('group_id', '==', item)
            | map(attribute='name')
            | list
          }}
      with_items: "{{ agency.group_join_to }}"
    - debug:
        msg: "机构 {{ agency.name }} 还将加入其它机构 {{ item }} 所在的群组。"
      loop: "{{ __join_to_agencies }}"

    # - name: 获取其它目标机构的节点列表
    #   set_fact:
    #     __join_to_nodes: >-
    #       {{ agencies
    #         | selectattr('group_id', '==', item)
    #         | sum(attribute='nodes', start=[])
    #         | list
    #       }}
    #   with_items: "{{ agency.group_join_to }}"
    # - debug:
    #     msg: "机构 {{ agency.name }} 还将加入其它机构的节点 {{ __join_to_nodes }}。"
  when:
    - agency.group_join_to is defined
    - agency.group_join_to != []
