- name: 生成创世区块
  command: "{{ item }}"
  with_items:
    - "./generator --create_group_genesis ./group"
  args:
    chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
  changed_when: false
  when:
    - inventory_hostname in groups['group_leader']
    - not __group_genesis_block_st.stat.exists

- name: 分发创世区块到相关从属机构
  copy:
    src: "{{ inventory_dir }}/agency_{{ __agency_leader_name }}/group/group.{{ agency_group_id }}.genesis"
    dest: "{{ inventory_dir }}/agency_{{ agency_name }}/meta/group.{{ agency_group_id }}.genesis"
  delegate_to: localhost
  when: inventory_hostname in groups['group_follower']
