- block:
    - name: 安装 generator
      command: bash ./scripts/install.sh
      args:
        chdir: "{{ inventory_dir }}/generator"
      register: __command_result

    - name: 获取最新的 fisco-bcos 执行文件
      command: ./generator --download_fisco ./meta --cdn
      args:
        chdir: "{{ inventory_dir }}/generator"
      changed_when: false
