- name: "检查 generator 目录"
  stat:
    path: "{{ fisco_workdir }}/generator"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir

# - name: "检查创世区块是否已生成"
#   stat:
#     path: "{{ fisco_workdir }}/agency_{{ item.name }}/group/group.{{ item.group_id }}.genesis"
#     get_attributes: false
#     get_checksum: false
#     get_mime: false
#   register: __group_genesis_block_st
#   when: item.create_genesis | default(false)
#   loop: "{{ agencies }}"
#   loop_control:
#     label: "机构 {{ item.name }}"
