- block:
    - name: "检查 {{ inventory_dir }}/generator"
      stat:
        path: "{{ inventory_dir }}/generator"
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: __generator_dir

    - name: "Checking {{ inventory_dir }}/generator/dir_chain_ca/"
      stat:
        path: "{{ inventory_dir }}/generator/dir_chain_ca/"
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: __dir_chain_ca_dir

    - name: "检查 {{ inventory_dir }}/generator/dir_agency_ca/agency_{{ agency_name }}"
      stat:
        path: "{{ inventory_dir }}/generator/dir_agency_ca/agency_{{ agency_name }}"
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: __dir_agency_ca_dir

  run_once: true

- name: "检查创世区块是否已生成"
  stat:
    path: "{{ inventory_dir }}/agency_{{ agency_name }}/group/group.{{ agency_group_id }}.genesis"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __group_genesis_block_st
  when: inventory_hostname in groups['group_leader']
