- block:

    - name: Create/update agency
      file:
        path: "{{ inventory_dir }}/agency_{{ agency_name }}"
        state: directory

    - name: Generating node files
      shell: "{{ item }}"
      with_items:
        - "rsync -a --exclude dir_chain_ca --exclude dir_agency_ca --exclude tmp_one_click --exclude 'node_deployment.ini' {{ inventory_dir }}/generator/ {{ inventory_dir }}/agency_{{ agency_name }}/"
        - "./generator --generate_chain_certificate ./dir_chain_ca"
        - "./generator --generate_agency_certificate ./dir_agency_ca ./dir_chain_ca agency_{{ agency_name }}"
        - "cp ./dir_agency_ca/agency_{{ agency_name }}/* {{ inventory_dir }}/agency_{{ agency_name }}/meta/"
      args:
        chdir: "{{ inventory_dir }}/generator/"
        warn: false
      changed_when: false

    - name: Create/update node_deployment.ini
      template:
        src: node_deployment.ini.j2
        dest: "{{ inventory_dir }}/agency_{{ agency_name }}/conf/node_deployment.ini"
        backup: true
        mode: 0666

    - name: Generating agency node info
      command: "{{ item }}"
      with_items:
        - "./generator --generate_all_certificates ./agency_{{ agency_name }}_node_info"
      args:
        chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
      changed_when: false

  rescue:

    - include_tasks: enterprise/install_generator.yml
    - include_tasks: enterprise/agency_init.yml
