- block:
    - name: "Sync files from {{ inventory_dir }}/generator/ to {{ inventory_dir }}/agency_{{ agency_name }}/"
      command: >-
        rsync -a --exclude-from '{{ role_path }}/files/rsync-exclude-list.txt' \
          {{ inventory_dir }}/generator/ {{ inventory_dir }}/agency_{{ agency_name }}/
      args:
        chdir: "{{ inventory_dir }}/generator/"
        warn: false
      changed_when: false

    - name: Generating chain certificates
      when: not __dir_chain_ca_dir.stat.exists
      command: "./generator --generate_chain_certificate ./dir_chain_ca"
      args:
        chdir: "{{ inventory_dir }}/generator/"
        warn: false
      changed_when: false

    - name: Generating agency certificates
      when: not __dir_agency_ca_dir.stat.exists
      command: "./generator --generate_agency_certificate ./dir_agency_ca ./dir_chain_ca agency_{{ agency_name }}"
      args:
        chdir: "{{ inventory_dir }}/generator/"
        warn: false
      changed_when: false

    - name: "Copy agency certificates to {{ inventory_dir }}/agency_{{ agency_name }}/meta/"
      when: "lookup('fileglob', inventory_dir + '/agency_' + agency_name + '/meta/agency.*') == []"
      shell: "cp {{ inventory_dir }}/generator/dir_agency_ca/agency_{{ agency_name }}/* {{ inventory_dir }}/agency_{{ agency_name }}/meta/"
      args:
        warn: false
      changed_when: false

    - name: "Create/update {{ inventory_dir }}/agency_{{ agency_name }}/conf/node_deployment.ini"
      template:
        src: "node_deployment.ini.j2"
        dest: "{{ inventory_dir }}/agency_{{ agency_name }}/conf/node_deployment.ini"
        mode: 0600

    - name: Generating agency node info
      command: "{{ item }}"
      with_items:
        - "./generator --generate_all_certificates {{ inventory_dir }}/agency_{{ agency_name }}/agency_{{ agency_name }}_node_info"
      args:
        chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
      changed_when: false
      register: __command_result
      failed_when: "'ERROR' in __command_result"

    - name: Set local fact of ca files
      set_fact:
        __dir_chain_ca_st: "{{ lookup('fileglob', '{{ inventory_dir }}/generator/dir_chain_ca/ca.*') }}"
        __dir_agency_ca_st: "{{ lookup('fileglob', '{{ inventory_dir }}/generator/dir_agency_ca/') }}"

    - name: Send files between leader and follower
      shell: "{{ item }}"
      args:
        warn: false
      with_items:
        - "cp {{ inventory_dir }}/agency_{{ __agency_leader_name }}/agency_{{ __agency_leader_name }}_node_info/peers.txt {{ inventory_dir }}/agency_{{ agency_name }}/meta/peers_{{ __agency_leader_name }}.txt"
        - "cp {{ inventory_dir }}/agency_{{ agency_name }}/agency_{{ agency_name }}_node_info/peers.txt {{ inventory_dir }}/agency_{{ __agency_leader_name }}/meta/peers_{{ agency_name }}.txt"
        - "cp {{ inventory_dir }}/agency_{{ agency_name }}/agency_{{ agency_name }}_node_info/cert*.crt {{ inventory_dir }}/agency_{{ __agency_leader_name }}/meta/"
      delegate_to: localhost
      when: inventory_hostname in groups['group_genesis_follower']
      changed_when: false

  when: group_now in groups
