- block:
    - name: Create/update group_genesis.ini
      template:
        src: group_genesis.ini.j2
        dest: "{{ inventory_dir }}/agency_{{ agency_name }}/conf/group_genesis.ini"
        backup: true
        mode: 0666

    - name: Generating group genesis
      command: "{{ item }}"
      with_items:
        - "./generator --create_group_genesis ./group"
      args:
        chdir: "{{ inventory_dir }}/agency_{{ agency_name }}"
      changed_when: false
      register: __command_result
      failed_when: "'ERROR' in __command_result"
  when: inventory_hostname in groups['group_genesis_creator']

- name: Transfer genesis block to other agency under the same group
  command: >-
    cp {{ inventory_dir }}/agency_{{ __agency_leader_name }}/group/group.{{ agency_group_id }}.genesis \
      {{ inventory_dir }}/agency_{{ agency_name }}/meta/group.{{ agency_group_id }}.genesis
  args:
    warn: false
  delegate_to: localhost
  when: inventory_hostname in groups['group_genesis_follower']
