- name: Set minimum and maximun agency group id
  set_fact:
    __agency_group_id_min: >-
      {{ groups['all']
          | map('extract', hostvars)
          | map(attribute='agency_group_id')
          | list
          | min
      }}
    __agency_group_id_max: >-
      {{ groups['all']
          | map('extract', hostvars)
          | map(attribute='agency_group_id')
          | list
          | max
      }}

- name: Group hosts by group ID
  group_by:
    key: "{{ item }}"
  with_items:
    - "group_{{ agency_genesis | default(false) | ternary('genesis_creator', 'genesis_follower') }}"
    - "group_{{ agency_group_id }}"
  changed_when: false

# - name: Set local facts
#   set_fact:
#     __dir_chain_ca_st: "{{ lookup('fileglob', '{{ inventory_dir }}/generator/dir_chain_ca/ca.*') | default([]) }}"
#     __dir_agency_ca_st: "{{ lookup('fileglob', '{{ inventory_dir }}/generator/dir_agency_ca/') | default([]) }}"

- name: Set agency leader fact
  set_fact:
    __agency_leader_name: >-
      {{ groups['group_genesis_creator']
          | map('extract', hostvars)
          | selectattr('agency_group_id', 'equalto', agency_group_id)
          | map(attribute='agency_name')
          | list
          | first
      }}
    __agency_leader_info: >-
      {{ groups['group_genesis_creator']
          | map('extract', hostvars)
          | selectattr('agency_group_id', 'equalto', agency_group_id)
          | map(attribute='agency_nodes')
          | list
          | first
      }}
  when:
    - inventory_hostname in groups['group_genesis_follower']

- name: Set agency follower fact
  set_fact:
    __agency_follower_name: >-
      {{ groups['group_genesis_follower']
          | map('extract', hostvars)
          | selectattr('agency_group_id', 'equalto', agency_group_id)
          | map(attribute='agency_name')
          | list
      }}
    __agency_follower_info: >-
      {{ groups['group_genesis_follower']
          | map('extract', hostvars)
          | selectattr('agency_group_id', 'equalto', agency_group_id)
          | map(attribute='agency_nodes')
          | list
      }}
  when: inventory_hostname in groups['group_genesis_creator']
