- name: "Checking {{ inventory_dir }}/generator"
  stat:
    path: "{{ inventory_dir }}/generator"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir

- name: "Checking {{ inventory_dir }}/generator/dir_chain_ca/"
  stat:
    path: "{{ inventory_dir }}/generator/dir_chain_ca/"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __dir_chain_ca_dir

- name: "Checking {{ inventory_dir }}/generator/dir_agency_ca/agency_{{ agency_name }}"
  stat:
    path: "{{ inventory_dir }}/generator/dir_agency_ca/agency_{{ agency_name }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __dir_agency_ca_dir
