- block:
    - name: Install generator
      command: bash ./scripts/install.sh
      args:
        chdir: /tmp/generator
      changed_when: false

    - name: Pull the latest fisco-bcos binary to the meta
      comand: ./generator --download_fisco ./meta
      args:
        chdir: /tmp/generator
      changed_when: false

  rescue:

    - include_tasks: prepare.yml

  delegate_to: localhost
  become: false
