- name: Group hosts by group ID
  group_by:
    key: "{{ item }}"
  with_items:
    - "group_{{ agency_genesis | default(false) | ternary('genesis_creator', 'genesis_follower') }}"
    - "group_{{ agency_group_id }}"
  changed_when: false

- block:
    - include_tasks: enterprise/agency_init.yml
    - include_tasks: enterprise/genesis_init.yml
  delegate_to: localhost
