- block:
    - name: "Create {{ ansible_user_dir }}/fisco"
      file:
        path: "{{ ansible_user_dir }}/fisco"
        state: directory

    - name: Installing tools
      package:
        name:
          - openssl
          - curl
          - default-jdk

    - name: Downloading build_chain.sh script
      get_url:
        url: "{{ fisco_build_chain_url }}"
        dest: "{{ ansible_user_dir }}/fisco/"

    - name: Downloading download_console.sh
      get_url:
        url: "{{ fisco_download_console_url }}"
        dest: "{{ ansible_user_dir }}/fisco/"
  when: fisco_deploy_mode == 'single'
  run_once: true

- block:
    - name: Install tools
      package:
        name:
          - git
          - openssl
          - curl
          - python3

    - name: Clone/update generator
      become: false
      git:
        repo: "{{ fisco_generator_git }}"
        dest: "{{ inventory_dir }}/generator"
        depth: 1
  when: fisco_deploy_mode == 'enterprise'
  run_once: true
  delegate_to: localhost
