# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: all.yml
# @Last modified by:   haibin
# @Last modified time: 2020-11-17T12:25:46+08:00
# @License: GNU General Public License v3.0



# ansible_python_interpreter: python3

fisco_deploy_mode: enterprise
