# true 表示使用国密模式
fisco_gm_enabled: true

# 变量注释
# name:           （必填）机构名称
# create_genesis: 是否生成创世区块，同组必须有且只有 1 个创世区块机构。（不设置则默认为 false）
# nodes:          （必填）机构各节点连接信息。格式 <ip>:<节点数>。如果只填写 IP，则默认为 1 个节点。同 IP 多节点会自动递增对应端口。參考 https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/enterprise_tools/tutorial_detail_operation.html#id5。生产环境中请确保各机构不共用服务器，避免私钥证书的泄漏。由于节点多群组共享网络带宽、CPU和内存资源，因此为了保证服务的稳定性，一台机器上不推荐配置过多节点。
# group_id:       （必填）群组编号
# group_join_to:  （可选）额外要加入的目标群组编号

agencies:
  - name: A
    create_genesis: true
    nodes:
      - 172.17.8.101:3
      - 172.17.8.102:3
    group_id: 1
    group_join_to:
      - 2
  - name: B
    nodes:
      - 172.17.8.103:3
      - 172.17.8.104:3
    group_id: 1
  - name: C
    create_genesis: true
    nodes:
      - 172.17.8.105:3
      - 172.17.8.106:3
      - 172.17.8.107:3
    group_id: 2
