# @Author: Haibin Lee <haibin>
# @Date:   2020-12-04T13:09:45+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: 2.7.0.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-04T13:09:47+08:00
# @Copyright: Copyright 2020 the original author or authors.
