- block:
    - include_tasks: enterprise/set_stat.yml

- include_tasks: enterprise/generate_agency_certificate.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_initialed

- include_tasks: enterprise/generate_agency_config.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_initialed

- include_tasks: enterprise/generate_peers_file.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_initialed

- include_tasks: enterprise/generate_genesis.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_initialed

- include_tasks: enterprise/build_install_package.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_initialed

- include_tasks: enterprise/expand_node.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when:
    - new_node_list != []
    - agency.name in agency_initialed
    - new_node_list | regex_search(agency.name + ':', multiline=True, ignorecase=True)

- include_tasks: enterprise/post_job.yml

# - name: 打包部署文件
#   archive:
#     path: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}"
#     dest: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
#   loop: "{{ agencies }}"
#   loop_control:
#     loop_var: agency
#     label: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
