- block:
    - include_tasks: enterprise/set_stat.yml

- block:
    - include_tasks: enterprise/install_generator.yml
  when: not __generator_dir.stat.exists

- include_tasks: enterprise/agency_init.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency

- name: 打包部署文件
  archive:
    path: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}"
    dest: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
